# -*- coding: utf-8 -*-
"""20221CIT0072(LABSHEET03)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANcUsqbhwqlVmdRe3rTIoesL89hkwMkP
"""

#Note
#1 importing the data set
#2 create the data frame
#3 get insite of the data
#4 perform EDA=exploratory data analysis
#5 split the data into training and testig
#6 make the model=> 1) create fit
                    #2) predict
                    #3) accuracy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/advertising.csv')

df.head(10)

df.info()

print(df.shape)

print(df.describe())

# OUTLIER ANALYSIS
fig, ax = plt.subplots(figsize=(10,10)) # Only create one subplot

sns.boxplot(df['TV'], ax=ax)
sns.boxplot(df['Newspaper'], ax=ax)
sns.boxplot(df['Radio'], ax=ax)

plt.tight_layout()

x=df['TV']
y=df['Sales']

#plot bt x and y
plt.scatter(x,y,color = 'blue',label='scatter plot')
plt.title('relationship between TV and sales')
plt.xlabel('TV')
plt.ylabel('Sales')
plt.legend()
plt.show()

print(x.shape)
print(y.shape)

x=np.array(x)
y=np.array(y)

x=x.reshape(-1,1)
y=y.reshape(-1,1)

print(x.shape)
print(y.shape)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
plt.show()

from sklearn.linear_model import LinearRegression
lm=LinearRegression()
lm.fit(x_train,y_train)
plt.scatter(x_train,y_train,color='red')
plt.plot(x_train,lm.predict(x_train),color='blue')
plt.show()

plt.scatter(x_test,y_test,color='red')
plt.plot(x_train,lm.predict(x_train),color='blue')
plt.title('test set results')
plt.xlabel('TV')
plt.ylabel('Sales')
plt.show()

slope = lm.coef_
intercept = lm.intercept_,
print("estimated model slope:",slope)
print("estimated model intercept:",intercept)
print(slope)
print(intercept)