# -*- coding: utf-8 -*-
"""20221cit0072[04]

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18spgjP8ZM40HzHRgUpCSJr2Y9geiZVCE
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
df=pd.read_csv("/content/German_Credit_Card_Dataset.csv")
df.info()
df.head()
df.shape

df.iloc[0:5,0:7]

df.iloc[0:5,7:]

df.iloc[0:5,7:15]

import pandas as pd # imports pandas module
df=pd.read_csv("/content/German_Credit_Card_Dataset.csv") # reads a csv file into a pandas DataFrame
df.info() # prints information about the DataFrame
df.head() # prints the first 5 rows of the DataFrame
df.shape # prints the dimensions of the DataFrame
df.iloc[0:5,0:7] # slices the DataFrame
df.iloc[0:5,7:] # slices the DataFrame
df.iloc[0:5,7:15] # slices the DataFrame
df['checkin_acc'].unique() # returns the unique values in the 'checkin_acc' column
import numpy as np # imports the numpy module and aliases it as np
np.array(['A11','A12','A13'],dtype=object) # creates a numpy array

x_feature=list(df.columns)
x_feature.remove('status')
encode_df=pd.get_dummies(df[x_feature],drop_first=True)
print(list(encode_df.columns))

x=encode_df
y=df['status']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier(criterion='gini',max_depth=3)
clf.fit(x_train,y_train)

pred=clf.predict(x_test)

from sklearn import metrics
print("confusion matrix is\n",metrics.confusion_matrix(pred,y_test)) # Changed pred_y to pred
print("accuracy is",metrics.accuracy_score(y_test, pred)) # Changed pred_y to y_test and y_pred to pred

from sklearn.tree import export_graphviz
import pydotplus as pdot
from IPython.display import Image
export_graphviz(clf,out_file="tree.dot",feature_names=list(x_train.columns),impurity=False,filled=True)
graph=pdot.graphviz.graph_from_dot_file("tree.dot")
graph.write_png("tree.png")
Image(filename="tree.png")

